name: Build macOS DMG

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-13

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.2'
        target: 'desktop'
        arch: 'clang_64'

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Deploy Qt & Make DMG
      run: |
        cd build
        # .app folder နာမည်ကို အတိအကျ ရှာပြီး Deploy ပြုလုပ်ခြင်း
        APP_PATH=$(find . -name "*.app" -maxdepth 2)
        echo "Found app at: $APP_PATH"
        macdeployqt "$APP_PATH" -qmldir=../ -dmg

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtMirrorApp-Mac-DMG
        path: build/*.dmg
