name: Build macOS DMG

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-13

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        target: 'desktop'
        arch: 'clang_64'

    - name: Build macOS App & Generate DMG
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        macdeployqt appQtMirrorApp.app -dmg

    - name: Upload DMG Artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtMirrorApp-Mac-DMG
        path: build/*.dmg